{
 "title": "Kafka Connect Cluster - Sink Connector",
 "tags": [
  "kafka",
  "connect_cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\", cluster_id=\"$cluster_id\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka-connect\", cluster_id=~\"connect-cluster\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Put Batch Average time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_put_batch_avg_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Put Batch Max time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_put_batch_max_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_partition_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}