{
 "title": "Kafka - Topic",
 "tags": [
  "Kafka Cluster",
  "Kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic!~\"__confluent.+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Topic Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kafka_log_log_value{name=\"Size\", topic=~ '$topic'}) by (partition))"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kafka_log_log_value{name=\"Size\", topic='$topic'}) by (partition))"
    }
   ]
  },
  {
   "title": "offset difference",
   "type": "singlestat",
   "description": "Only pertains to non-compacted topics",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kafka_log_log_value{name=\"LogEndOffset\", topic =~ \"$topic\"}) by (partition)) - sum(max(kafka_log_log_value{name=\"LogStartOffset\", topic =~ \"$topic\"}) by (partition))"
    }
   ]
  },
  {
   "title": "Total Messages (of all time)",
   "type": "singlestat",
   "description": "Only pertains to non-compacted topics",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max by(partition)(kafka_log_log_value{name=\"LogEndOffset\", topic =~ \"$topic\"}))"
    }
   ]
  },
  {
   "title": "Log Segments",
   "type": "singlestat",
   "description": "Only pertains to non-compacted topics",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_log_value{name=\"NumLogSegments\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "messages in / sec",
   "type": "singlestat",
   "description": "Based on the 1-minute rate from Kafka",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",topic = \"${topic}\"})"
    }
   ]
  },
  {
   "title": "bytes in / sec",
   "type": "singlestat",
   "description": "Based on the 1-minute rate from Kafka",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic = \"${topic}\"})"
    }
   ]
  },
  {
   "title": "bytes out / sec",
   "type": "singlestat",
   "description": "Based on the 1-minute rate from Kafka",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic = \"${topic}\"})"
    }
   ]
  },
  {
   "title": "Messages In - ${topic}",
   "type": "graph",
   "description": "This is based on the One Minute Rate value from the Kafka Broker.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",topic = \"${topic}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In - ${topic}",
   "type": "graph",
   "description": "This is based on the One Minute Rate value from the Kafka Broker.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic = \"${topic}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out - ${topic}",
   "type": "graph",
   "description": "This is based on the One Minute Rate value from the Kafka Broker.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic = \"${topic}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "messages in / sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\",topic = \"${topic}\"}[1m]))"
    }
   ]
  },
  {
   "title": "bytes in / sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 12 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"BytesInPerSec\",topic = \"${topic}\"}[1m]))"
    }
   ]
  },
  {
   "title": "bytes out / sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"BytesOutPerSec\",topic = \"${topic}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Messages In - ${topic}",
   "type": "graph",
   "description": "This is based on the Count from the broker and Grafana doing the time series calculation with a 1-minute interval.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\", topic = \"${topic}\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In - ${topic}",
   "type": "graph",
   "description": "This is based on the Count from the broker and Grafana doing the time series calculation with a 1-minute interval.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_count{name=\"BytesInPerSec\", topic = \"${topic}\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out - ${topic}",
   "type": "graph",
   "description": "This is based on the Count from the broker and Grafana doing the time series calculation with a 1-minute interval.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_count{name=\"BytesOutPerSec\", topic = \"${topic}\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}