{
 "title": "Kafka Cluster - Overview",
 "description": "Apache Kafka resource usage and throughput",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_value{name=\"LeaderCount\",})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_count{name=\"UncleanLeaderElectionsPerSec\",})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"PartitionCount\",})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\",})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"OfflinePartitionsCount\",})"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",topic=\"\"})"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic=\"\"})"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\",topic!~\"(_)+confluent.+\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic!~\"(_)+confluent.+\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic!~\"(_)+confluent.+\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_log_value{name=\"Size\", topic!~\"(_)+confluent.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (kafka_log_log_value{name=\"Size\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_cluster_partition_value{name=\"UnderReplicated\",topic!~\"(_)+confluent.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_oneminuterate{name=\"IsrExpandsPerSec\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions / Leaders / Under Replicas",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_replicamanager_value{name=\"PartitionCount\",})"
    },
    {
     "expr": "sum by(instance) (kafka_server_replicamanager_value{name=\"LeaderCount\",})"
    },
    {
     "expr": "sum by(instance) (kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\",})"
    }
   ]
  },
  {
   "title": "Purgatory Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_delayedoperationpurgatory_value{name=\"PurgatorySize\",delayedOperation=~\"(.+)\"})",
     "legendFormat": "{{delayedOperation}}"
    }
   ]
  }
 ]
}