networks:
  default:
    external: true
    name: kafka-local

volumes:
  cassandra_data: {}
  etc: {}

services:
  cassandra3:
    image: cassandra:3.11.13
    hostname: cassandra3
    container_name: cassandra3
    ports:
      - "9042:9042"  
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - ./cassandra.yaml:/opt/cassandra/conf/cassandra.yaml
      - cassandra_data:/var/lib/cassandra    
      - etc:/etc/cassandra   
      - ./data:/data
      - ./debezium:/debezium
    environment:
      CASSANDRA_CLUSTER_NAME: cassandra
      CASSANDRA_DATACENTER: dc_main
      CASSANDRA_PASSWORD: cassandra
#      CASSANDRA_SEEDS: "cass1,cass2"    
#      CASSANDRA_RACK: West
#      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
#      CASSANDRA_NUM_TOKENS: 128
