---
version: '3.7'

networks:
  default:
    external: true
    name: kafka-local

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl -s -f http://localhost:9200/_cat/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 15s
    environment:
      xpack.security.enabled: "false"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.1
    hostname: kibana
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    healthcheck:
      test: curl -s -f http://localhost:5601/login || exit 1
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 15s
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
