---
version: '3.7'

networks:
  default:
    external: true
    name: kafka-local

services:

  fake-gcs-server:
    image: fsouza/fake-gcs-server:v1.30.1
    container_name: fake-gcs-server
    hostname: fake-gcs-server
    ports:
      - "8001:8001"
    volumes:
      - ./data:/data
    command: -port 8001 -scheme http -external-url http://fake-gcs-server:8001

  cloudserver:
    image: zenko/cloudserver:latest
    container_name: cloudserver
    hostname: cloudserver
    ports:
      - "8000:8000"
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=secretKey1
      - S3BACKEND=mem
      - LOG_LEVEL=trace
      - REMOTE_MANAGEMENT_DISABLE=1
    volumes:
      - ./cloudserver/data:/data
      - ./cloudserver/metadata:/metadata

  localstack:
    image: localstack/localstack:0.12.12
    container_name: localstack
    hostname: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/data
      - PORT_WEB_UI=
      - LAMBDA_EXECUTOR=
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./data:/data
#      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

