{
 "title": "Kafka Connect Cluster - Connector BK",
 "tags": [
  "kafka",
  "connect_cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\", cluster_id=\"$cluster_id\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka-connect\", cluster_id=~\"connect-cluster\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_metrics{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",connector_type!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "kafka_connect_connector_metrics{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",connector_version!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_metrics{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",connector_class!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_total_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "label_replace(label_replace(label_replace(kafka_connect_connector_info{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",status!=\"\"}, \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
    }
   ]
  },
  { "title": "Task metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_avg{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_max{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit success percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Poll Batch Average time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_poll_batch_avg_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Poll Batch Max time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_poll_batch_max_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Poll rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_poll_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Write rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_write_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Active Count average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_active_count_avg{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Active Count max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_active_count_max{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sink metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partition Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_partition_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Average time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_avg_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Max time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_max_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  { "title": "Task Errors metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_failures{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_errors{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_records_skipped{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_errors_logged{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_retries{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_deadletterqueue_produce_requests{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}