---
version: '3.7'

networks:
  default:
    external: true
    name: kafka-local

services:
  jobmanager:
    image: flink:1.14.0-scala_2.12-java11
    container_name: flink_jobmanager
    ports:
      - "48081:8081"
      - "46123:6123"
      - "46124:6124"
      - "46125:6125"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./jars:/jars
      - ./data:/data
      - ./tmp:/Users/buesing/workspaces/gorillio/beam-pipelines/pipeline

  taskmanager:
    image: flink:1.14.0-scala_2.12-java11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
        taskmanager.memory.network.max: 268435460b
        taskmanager.memory.network.min: 268435460b
        taskmanager.memory.network.fraction: .4
        cluster.evenly-spread-out-slots: true
    volumes:
      - ./jars:/jars
      - ./data:/data
#      - ./tmp:/Users/buesing/workspaces/gorillio/beam-pipelines/pipeline
